### ISSUE TITLE
MKL_CBWR setting

### ISSUE THREAD

**Issue by powerreactor** [uoguelph-mlrg/Theano-MPI#12]
Hi He,

Currently you set MKL_CBWR to COMPATIBLE. What is the testing result for using AUTO on Copper?

If AUTO shows no difference compared to COMPATIBLE, please change it to AUTO.

**Comment by hma02** [comment]
I tested MKL_CBWR=AUTO when training AlexNet on 8GPUs. It gives the same top-5 error 20.7% as MKL_CBWR=COMPATIBLE. Changed 79ec9e9.
