### ISSUE TITLE
Error with adjust_lr() fuction

### ISSUE THREAD

**Issue by powerreactor** [uoguelph-mlrg/Theano-MPI#17]
Hi He,

When I test new backend with googlenet. I got error:
 File "../lib/BSP_Worker.py", line 406, in adjust_lr
    self.model.adjust_lr(self.epoch)
TypeError: adjust_lr() takes exactly 3 arguments (2 given)

Can you please take look and fix it?

Thanks,
Fei

**Comment by hma02** [comment]
@powerreactor 

Hi Fei, just fixed. See 1d0cda9
