### ISSUE TITLE
ImportError: No module named 'rules'

### ISSUE THREAD

**Issue by dlunga** [uoguelph-mlrg/Theano-MPI#19]
Hi,

I am running into an import error in python3. Not sure if I needed to restructure my folders after installing?

> from theanompi import BSP
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/home/theanompi/__init__.py", line 1, in <module>
>     from rules import BSP, EASGD, GOSGD
> ImportError: No module named 'rules'

Same command works fine when executed in python2.7

**Comment by hma02** [comment]
@dlunga 

Sorry. I haven't tried working with python3 yet. I will look into this problem.

**Comment by hma02** [comment]
@dlunga 

This commit should fix it: https://github.com/uoguelph-mlrg/Theano-MPI/commit/af5576d2c36c3835f000015d76a5241566e90d18#diff-4d9375831f7078f460af6d167a98f2c9R1

**Comment by dlunga** [comment]
Thanks for the fix. All good. Great library by the way! Do you mind if we connect offline.

**Comment by hma02** [comment]
@dlunga 

Thanks. Glad it can be of use to you. Sure. You can reach me at hma02@uoguelph.ca.
